name = "warroom-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "55f4e15ce53f10a387526d8b1bcfdb17"

[dev]
port = 8791
local_protocol = "http"

[env.production]
name = "warroom-api"

[[d1_databases]]
binding = "DB"
database_name = "warroom-db"
database_id = "3fe6424e-c2db-47d7-be7f-23339c29fa16"

[vars]
ALLOWED_ORIGINS = "https://rogueff.github.io,http://localhost:3000,http://localhost:5500,http://localhost:8080"
