name = "mission-control-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "55f4e15ce53f10a387526d8b1bcfdb17"

[dev]
port = 8788
local_protocol = "http"

[env.production]
name = "mission-control-api"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "mission-control-db"
database_id = "1574e8f7-f2f8-4663-8187-b0a00793ea64"

# CORS configuration
[vars]
ALLOWED_ORIGINS = "https://rogueff.github.io,http://localhost:3000,http://localhost:5500,http://localhost:8080"
